@startuml
left to right direction

actor AnonymousVisitor as av
actor AuthentifiedVisitor as au
actor SysAdmin as sa

av <|-- au
au <|-- sa

package flask_petclinic {

    package petclinic_visit {

        usecase visit_search as uc6000
        usecase visit_list as uc6001
        usecase visit_new as uc6002

        au -- uc6000
        au -- uc6001
        au -- uc6002

        uc6001 <-- uc6000
        uc6001 <-- uc6002
    }

}
@enduml
