@startuml
left to right direction

actor AnonymousVisitor as av
actor AuthentifiedVisitor as au
actor SysAdmin as sa

av <|-- au
au <|-- sa

package flask_petclinic {

    package petclinic_visit {

        usecase visit_search as uc6000
        usecase visit_list as uc6001
        usecase visit_new as uc6002
        usecase visit_show as uc6003
        usecase visit_change as uc6004

        au --> uc6000
        au --> uc6001
        au --> uc6002
        au --> uc6003
        au --> uc6004

    }

    package petclinic_pet_visit {

        usecase pet_list_visits as uc6020
        usecase pet_add_visit_to_pet_and_vet as uc6021
        usecase pet_change_visit_to_pet_and_vet as uc6022

        au --> uc6020
        au --> uc6021
        au --> uc6022
    }

}
@enduml
