@startuml
left to right direction

actor AnonymousVisitor as av
actor AuthentifiedVisitor as au
actor SysAdmin as sa

av <|-- au
au <|-- sa

package flask_petclinic {

    package flask_petclinic.pet {
        usecase pet_search as uc5000
        usecase pet_list as uc5001
        usecase pet_new as uc5002
        usecase url_pet_show as uc5003
        usecase pet_change as uc5004
        usecase pet_choose_pettype as uc5005

        au -- uc5000
        au -- uc5001
        ' au -- uc5002
        au -- uc5003

        uc5001 <-- uc5000
        uc5001 <-- uc5002
        uc5001 <-- uc5003
        uc5003 <-- uc5004
        uc5002 --> uc5005
        uc5004 --> uc5005
    }
}
@enduml
