@startuml
left to right direction

actor AnonymousVisitor as av
actor AuthentifiedVisitor as au
actor SysAdmin as sa

av <|-- au
au <|-- sa

package flask_petclinic {

    package flask_petclinic.pet {
        usecase pet_search as uc5000
        usecase pet_list as uc5001
        usecase pet_new as uc5002
        usecase pet_show as uc5003
        usecase pet_change as uc5004
        usecase pet_choose_pettype as uc5006

        au --> uc5000
        au --> uc5001
        au --> uc5002
        au --> uc5003
        au --> uc5004

        uc5002 --> uc5006
        uc5003 --> uc5006
    }
}
@enduml
