@startuml
left to right direction

actor AnonymousVisitor as av
actor AuthentifiedVisitor as au
actor SysAdmin as sa

av <|-- au
au <|-- sa

package flask_petclinic {

    package petclinic_specialty {
        usecase specialty_search as uc2000
        usecase specialty_list as uc2001
        usecase specialty_new as uc2002
        usecase specialty_show as uc2003

        au --> uc2000
        au --> uc2001
        au --> uc2002
        au --> uc2003
    }

}
@enduml
