@startuml
left to right direction

actor AnonymousVisitor as av
actor AuthentifiedVisitor as au
actor SysAdmin as sa

av <|-- au
au <|-- sa

package flask_petclinic {

    package petclinic_vet {
        usecase vet_search as uc3000
        usecase vet_list as uc3001
        usecase vet_new as uc3002
        usecase vet_change as uc3003
        usecase vet_choose_specialties as uc3004
        usecase vet_remove as uc3005

        au --> uc3000
        au --> uc3001
        au --> uc3002
        au --> uc3003
        uc3002 --> uc3004
        uc3003 --> uc3004
        au --> uc3005
    }

}
@enduml
