@startuml
left to right direction

actor AnonymousVisitor as av
actor AuthentifiedVisitor as au
actor SysAdmin as sa

av <|-- au
au <|-- sa

package flask_petclinic {

    package petclinic_owner {

        usecase owner_search as uc7000
        usecase owner_list as uc7001
        usecase owner_new as uc7002
        usecase owner_show as uc7003
        usecase owner_change as uc7004

        au -- uc7000
        au -- uc7001
        au -- uc7002

        uc7001 <-- uc7000
        uc7001 <-- uc7002
        uc7001 <-- uc7003
        uc7003 <-- uc7004
    }

    package petclinic_owner_pets {

        usecase owner_pet_list as uc7100
        usecase owner_pet_add_new as uc7101
        usecase owner_pet_show as uc7102
        usecase owner_pet_change as uc7103
        usecase owner_pet_give_to_another_owner as uc7104

        au -- uc7100
        au -- uc7101

        uc7003 --> uc7100
        uc7100 <-- uc7101
        uc7100 <-- uc7102
        uc7102 <-- uc7103
        uc7102 <-- uc7104
    }

    package petclinic_owner_pet_visits {

        usecase owner_pet_visits_list as uc7200
        usecase owner_pet_visits_add_new as uc7201

        au -- uc7200
        au -- uc7201

        uc7102 --> uc7200
        uc7200 <-- uc7201
    }

}
@enduml
