@startuml
left to right direction

actor AnonymousVisitor as av
actor AuthentifiedVisitor as au
actor SysAdmin as sa

av <|-- au
au <|-- sa

package flask_petclinic {

    package petclinic_pettype {
        usecase pettype_search as uc4000
        usecase pettype_list as uc4001
        usecase pettype_new as uc4002
        usecase pettype_change as uc4003

        au -- uc4000
        au -- uc4001
        au -- uc4002
        au -- uc4003

        uc4001 <-- uc4000
        uc4001 <-- uc4002
        uc4001 <-- uc4003
    }
}
@enduml
