@startuml
left to right direction

actor AnonymousVisitor as av
actor AuthentifiedVisitor as au
actor SysAdmin as sa

av <|-- au
au <|-- sa

package flask_petclinic {

    package app_web {
        usecase db_create as uc1200
        usecase db_drop_and_create as uc1201
        usecase db_dump as uc1202
        usecase db_dump_reimport as uc1203
        usecase db_table_count as uc1204

        sa --> uc1200
        sa --> uc1201
        sa --> uc1202
        sa --> uc1203
        sa --> uc1204
    }

}
@enduml
